# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomXibDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CustomXibDemo

  pod 'Masonry'

  target 'CustomXibDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CustomXibDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
